### ISSUE TITLE
ENHANCEMENT: Support ability to extend module

### ISSUE THREAD

**Issue by adunn49** [TheSceneman/silverstripe-glossary#1]
Hi Adrian,
Firstly, awesome work on this module - we've used it on a project - yay - and is looking really good, using [vue-popper](https://github.com/RobinCK/vue-popper) in the front end so that we could handle click events, auto-positioning of the popup, and a close button. (Note: we were using Vue2 so couldn't utilise https://headlessui.dev/vue/popover in frontend, which I know has been used on other projects for this kind of functionality).

One of the requirements we had was that the glossary popup in the front end supported WYSIWIG content (for styling and the ability to include links to other pages). For time constraints I simply forked the module and changed the field type for the 'Description' to be an HTMLText field, along with a few tweaks for being able to handle shortcode parsing and outputting the HTML field in the template.

Rather than assume the HTML field type is for everyone, perhaps a better way to handle this would be to add extension hooks at various points in this module, so that a HTML content field could be added if required. I've almost got this working and would be happy to raise a PR against this module, but wanted your thoughts on that approach versus simply changing the 'Description' field on GlossaryTerm to HTMLText.

Cheers

Andrew Dunn

**Comment by TheSceneman** [comment]
Hey Andrew
Thanks!

In all honesty I'm not sure why I set the `Description` as a `Varchar`. I think my original line of thinking was that brevity = good, therefore the intended use of this module was dictionary style snippets a la Google definitions and the like.

Since the front end of this module is basically wide open and intended to be customised, I think using `HTMLText` is a good idea, as this offers a lot more flexibility with no drawbacks (the floor is basically an unwanted `<p>` tag, perhaps).

I am interested in the extension hook solution as well though, and would be keen to see your implementation. Feel free to raise a PR with whatever!

Cheers
Adrian

**Comment by TheSceneman** [comment]
PR has been closed - Silverstripe DataExtension API covers a lot of what you've mentioned. DB fields can be overloaded and getCMSFields() has access to updateCMSFields() as part of SS framework, so I think we're good. https://api.silverstripe.org/4/SilverStripe/ORM/DataExtension.html
